### ISSUE TITLE
@conda-forge-admin, please add user @vpirogov

### ISSUE THREAD

**Issue by vpirogov** [conda-forge/onednn-feedstock#69]
### Additional comment:

I'm a maintainer of [oneDNN project](https://github.com/oneapi-src/oneDNN/blob/main/MAINTAINERS.md) and would like to manage conda-forge packages on behalf of the team.

**Comment by hmaarrfk** [comment]
it seems that you may work at the upstream onednn team.

I think the best way for you to be become a maintainer is to work through an issue on this feedstock, whether it be updating the version, optimizing some aspect of the build, so that others can review your work.

Simply "wanting to help" and "being an upstream developer" aren't the requirements for being a conda-forge maintainer. 

Core or the existing maintainers want to see you contribute in a meaningful way before handing over the keys.

**Comment by hmaarrfk** [comment]
Making PRs is free, this is how a maintainer would work on this feedstock in either way.

So when the time comes, you should be able to make one and make use of the bots to test the improvements you are suggesting.
